# .air.toml configuration file

# The command to run the application
cmd = "go run cmd/api/main.go"

# The patterns to watch
[watch]
  # Watch .go files in the current directory and subdirectories
  includes = [
    "**/*.go"
  ]

  # Exclude specific directories or files
  excludes = [
    "vendor/**",
    "tmp/**",
    "scripts/**"
  ]

# Customize logging
[log]
  # Log color settings
  color = true
  # Log timestamps
  time = true

# Set additional environment variables
[env]
  # Add any required environment variables here
  # Example:
  # APP_ENV = "development"

# Set build options
[build]
  # Build delay in milliseconds
  delay = 200

  # Binary name
  bin = "main"

  # Build the application with these tags
  tags = ""

  # Force rebuild on .go file changes
  full = false
