name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version:  [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - name: Install Dependencies
      run: npm ci
      working-directory: server  # Change to the server directory

    - name: Create .env File
      run: |
        touch server/.env
        echo "${{secrets.PROD_ENV_FILE}}" > server/.env

    - name: Build Server
      run: npm run build
      working-directory: server  # Build the server if applicable
